/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 backpack_lowpoly.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const path = 'models/backpack_lowpoly.glb'
export function BackPack(props) {
  const { nodes, materials } = useGLTF(path)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube001.geometry} material={materials.Material} position={[0, 1.36, -0.19]} scale={[0.11, 0.16, 0.06]} />
    </group>
  )
}

useGLTF.preload(path)
