/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/boyThrowingRecentredOrigin.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import * as THREE from 'three'
import { useThree } from '@react-three/fiber'

export function BoyThrowing(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/boyThrowingRecentredOrigin.glb')
  const { actions } = useAnimations(animations, group)
  let action = props.action

  const urls = {
    fullTrack: 'sound/Throwing sounds.mp3'
}
  const {camera} = useThree()
  // vanilla code
    const listener = new THREE.AudioListener()
    camera.add(listener)
    const audioLoader = new THREE.AudioLoader()

    const soundEffect = new THREE.Audio( listener )

    audioLoader.load(urls.fullTrack , function(buffer) {
      console.log("track loaded")
      soundEffect.setBuffer( buffer )
      soundEffect.setLoop( true )
      soundEffect.setVolume( 1 )
      // soundEffect.play()
    })

  useEffect(() =>
  {
    console.log(action)
    if (actions[action]) {
      // if (action == 'throw.001') { 
        // soundEffect.play()
      // }
      let currentAction = actions[action]
      currentAction.clampWhenFinished = true
      currentAction.setLoop(THREE.LoopOnce)
      currentAction.reset().play()
      if (action == 'throw.001') {
        // action rest
        let currentAction = actions["rest"]
        currentAction.clampWhenFinished = true
        currentAction.setLoop(THREE.LoopOnce)

        currentAction.reset().play()
      }
    }
  }, [action])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature002" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh name="Ch09" geometry={nodes.Ch09.geometry} material={materials['Ch09_body.001']} material-transparent material-opacity={0.3} skeleton={nodes.Ch09.skeleton}/>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/boyThrowingRecentredOrigin.glb')
