/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/boyThrowing.glb
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function BoyThrowing(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('models/boyThrowing.glb')
  const { actions } = useAnimations(animations, group)
  let action = props.action
  useEffect(() => {
    console.log(actions)
    actions[action]
    .play()
  }, [action])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig6Hips} />
          <skinnedMesh name="Ch09" geometry={nodes.Ch09.geometry} material={materials.Ch09_body} skeleton={nodes.Ch09.skeleton} />
        </group>
        <group name="Armature001" position={[0.6, 0.37, -1.81]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorig6Hips_1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('models/boyThrowing.glb')
