/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/paperguy.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Paperguy(props) {
  const { nodes, materials } = useGLTF('models/paperguy.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.peep_blinn3_0.geometry} material={materials.blinn3} position={[-10.1, 60.52, -0.72]} />
      </group>
    </group>
  )
}

useGLTF.preload('models/paperguy.glb')
