/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Scooter.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const path = 'models/Scooter.glb'

export function Scooter(props) {
  const { nodes, materials } = useGLTF(path)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Energy.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.06]} />
      <mesh geometry={nodes.RearWheel.geometry} material={materials.Scooter} position={[0.47, 0.15, 0.03]} />
      <mesh geometry={nodes.Fenders.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.FR_Wheel.geometry} material={materials.Scooter} position={[-1.22, -0.02, 0.03]} />
      <mesh geometry={nodes.FR_Rim.geometry} material={materials.Scooter} position={[-0.69, 0.06, 0.05]} />
      <mesh geometry={nodes.Body.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.BRDisk.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.BreakCapsl.geometry} material={materials.Scooter} position={[0.42, 0.19, 0.07]} />
      <mesh geometry={nodes.RearLight001.geometry} material={materials.Scooter} position={[0.61, 0.27, 0.03]} />
      <mesh geometry={nodes.Foodstp.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.handlebar002.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.clamp001.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.clamp002.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.handlebar001.geometry} material={materials.Scooter} position={[-0.42, 1.54, 0.03]} />
      <mesh geometry={nodes.handlebar.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.Bell.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.stick.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.02]} />
      <mesh geometry={nodes.RW_Rim.geometry} material={materials.Scooter} position={[0.47, 0.15, 0.03]} />
      <mesh geometry={nodes.Breaks.geometry} material={materials.Scooter} position={[-0.42, 1.54, 0.03]} />
      <mesh geometry={nodes.Glasses.geometry} material={materials.Scooter} position={[-0.47, 1.44, 0.02]} />
      <mesh geometry={nodes.Light.geometry} material={materials.Scooter} position={[-0.44, 1.45, 0.02]} />
      <mesh geometry={nodes.Body001.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.Foodstp001.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
      <mesh geometry={nodes.clamp.geometry} material={materials.Scooter} position={[-0.07, -0.02, 0.03]} />
    </group>
  )
}

useGLTF.preload(path)
